my @f_1 = ("szarrágó",
		"kis",
		"seggnyaló",
		"szájbakúrt",
		"baszott",
		"alkoholista",
		"gennyedző",
		"nyáladzó");
my @f_2 = ("hülye",
		"pöcs",
		"okádékkupac",
		"buzi",
		"faszfej",
		"húgyhólyag",
		"heregolyó",
		"puncipöcök",
		"szardarab",
		"fasz",
		"köcsög",
		"péniszpiszkáló",
		"spermaömleny",
		"foshalmaz",
		"segglyuk",
		"túristaszalámi",
		"ondóvezeték",
		"végbélkúp",
		"hüvelyváladék",
		"agyhalott");
my @f_3 = ("olyan vagy, mint",
		"úgy nézel ki, mint",
		"annyit érsz, mint",
		"nem érsz többet, mint");
my @f_4 = ("egy kis geci",
		"egy parazita",
		"egy nagy pattanás",
		"egy szétkent szardarab",
		"egy rothadó hulla",
		"egy kivert fasz",
		"Zámbó Jimmy",
		"egy bűzlő aranyér",
		"egy kettéhugyozott hóember",
		"egy főtt heregolyó",
		"egy marok geci");
my @f_5 = ("amit elleptek a döglegyek",
		"ami le van hugyozva",
		"amire ráverték a faszt",
		"ami szopat téged",
		"ami a pöcegödörben rohad",
		"ami a pofádba fingik",
		"ami szájbakúrta anyádat");
my @f_6 = ("kurvára",
		"legszívesebben",
		"ha most itt lennél",
		"ha nem csuknának le érte,",
		"jól",
		"kibaszottul",
		"ha elérnélek");
my @f_7 = ("szétverném a koponyádat",
		"kiloccsantanám az agyadat",
		"kiírtanám a családodat",
		"seggbebasználak a seprőnyéllel",
		"feldugnék neked egy esztergagépet",
		"belefosnák a pofádba",
		"teherbe basznám az anyádat és légkalapáccsal végeznék rajta abortuszt",
		"szétvágnálak, mit egy darab szart",
		"levégnám a farkad és a szádba varrnám",
		"sátánista szertartást végeznék nálatok",
		"belefújnám a taknyom a szádba",
		"úgy megbasználak, hogy a füledből is folyna a geci",
		"visszadugnálak anyádba, aki a világra szart",
		"feloldanálak kénsavban és lehúználak a budin mint a szaromat",
		"összetörnélek, mint egy kisköcsögöt",
		"a seggeden leresztül fordítanálak ki",
		"feldarabolnálak, elásnálak, majd lehugyoznám a sírodat",
		"lepépném a fejed és beleszarnék a nyelőcsövedbe");
my @f_8 = ("televert anyád",
		"halál",
		"hullamosó",
		"végbélrák",
		"csernobili mutánscsődör",
		"Micheal Jackson",
		"lepra",
		"seggbebaszott nagyapád",
		"húsvéti nyuszi",
		"rendőrezred",
		"kolera",
		"szarógörcs",
		"hígfosás",
		"bányarém",
		"cigányprímás",
		"hasmenéses víziló",
		"hétfejű sárkány",
		"kurva élet",
		"büdös kurva anyád",
		"trójai faló");
my @f_9 = ("baszna teherbe",
		"álljon beléd",
		"szárítsa le a farkadat",
		"rohasszon szét",
		"kúrna seggbe",
		"szívná ki anyádból a gecit",
		"fosson az arcodba",
		"döglesszen meg",
		"mászna beléd a seggeden",
		"marjon szét",
		"duzzassza meg a heréidet",
		"prücskölne meg",
		"ölne meg",
		"verje a melledre",
		"birizgáljon meg azzal a kibaszott nagy faszával",
		"húzna a faszára");
my @f10 = ("Meghajtalak, mint hegyipásztort a lavina" ,
		"Olyan sötét vagy, hogy a feketelyuk hozzád képest egy atomvillanás",
		"Folytál volna le apád térdén" ,
		"Olyan ronda vagy, hogy az etióp gyerek nem merné elvenni a kezedből a rántott húst",
		"Olyan csúnya vagy, hogy anyád is csak azért simogatott kiskorodban, hogy a testvéred ne féljen tőled",
		"Felrúglak, mint arab gyerek a tehénszart" ,
		"Kevés vagy, mint Hitlerben a jóindulat",
		"Gyenge vagy, mint a kannás bor",
		"Apád lehetnék, ha a kutya nem előz meg a lépcsőn",
		"Mássz vissza anyádba és kapartasd ki magad",
		"Olyan csúnya vagy, hogy az oroszlán is sírva enne meg",
		"Olyan sötét vagy, hogy a néger fasza hozzád képest egy neoncső",
		"Ledöntelek, mint 56-ban a Sztálin-szobrot",
		"Lecsaplak, mint a taknyot",
		"Lecsaplak, mint orosz hősugárzó a 10 amperes automatát",
		"Legyalázlak, mint brókert a tőzsdekrakk" ,
		"Eltaposlak, mint úthenger a házimacskát",
		"Szétszedlek, mint hülyegyerek a vécékefét",
		"Kiírtalak, mit urológus a végbélférget" ,
		"Letámadlak, mint pedofil az óvodást",
		"Lekezellek, mint háziorvos az aranyeret" ,
		"Hogy a Mária röhögjön rád" ,
		"Gitár nőjjön a mejjedbe, oszt a rák pengesse",
		"Eltaposlak, mint platós ZIL a cserebogarat",
		"Olyat rádfingok, hogy kipusztul az összes lapostetved",
		"Olyat beleböfögök abba a ragyás fejedbe, hogy kikönnyezed a fülzsírodat",
		"Olyat rádütök, hogy lefosod a bokád" ,
		"Hogy váltál volna szarrá anyádban",
		"Hogy az elefánt újjazna meg",
		"Olyan hülye vagy, hogyha ló lennél, tolnád a szekeret",
		"Olyan paraszt vagy, hogy kapálni lehetne veled",
		"Lefejellek, mint cigánygyerek a skinheadbakancsot",
		"Olyat rádütök, hogy kipusztulsz, mint a dinoszauruszok",
		"Lefejellek, mint naposcsibe a záptojást",
		"Megszállak, mint lószart a döglegyek");
my @f11 = ("Ne szóljál be",
		"Ne idegesíts",
		"Ne basszál fel még egyszer",
		"Nehogy elkapjalak",
		"Nehogy a szemem elé kerülj",
		"Ne szólj vissza");
my @f12 = ("szétbaszom a fejed",
		"olyat mondok, hogy megáll benned a szar",
		"olyat mondok, hogy rögtön tojsz egy húsvéti tojást",
		"lecsaplak, mint a taknyot",
		"megveszlek kilóra",
		"megleplek, mint Igort a tetvek",
		"megleplek, mint rothadó hullát a kukacok",
		"úgy megütlek, hogy a faszodon nő köröm",
		"megfejellek, mint részeg a kocsmaajtót",
		"megetetem veled a szaromat",
		"kitépem a beled és arra akasztalak fel",
		"az agyvelőddel mosom fel a padlót",
		"kettétörlek, mint a kapanyelet");

my $szoveg = 'te '. $f_1[int(rand(scalar @f_1))]
			. ' ' . $f_2[int(rand(scalar @f_2))]
			. ', '. $f_3[int(rand(scalar @f_3))]
			. ' ' . $f_4[int(rand(scalar @f_4))]
			. ' ' . $f_5[int(rand(scalar @f_5))]
			. ', '. $f_6[int(rand(scalar @f_6))]
			. ' ' . $f_7[int(rand(scalar @f_7))]
			. '! Hogy a ' .
					$f_8[int(rand(scalar @f_8))]
			. ' ' . $f_9[int(rand(scalar @f_9))] . '! '
				  . $f10[int(rand(scalar @f10))] . '!!!';

my $szoveg2 = 'Utóirat: ' . $f11[int(rand(scalar @f11))]
			  . ', mert ' . $f12[int(rand(scalar @f12))] . '!';

$out = $nick . ', ' . $szoveg . ' ' . $szoveg2;
